name: process with gitleaves

# Controls when the workflow will run
on:
  schedule:
    - cron: 0 0-23/4 * * *

# Triggers the workflow on a push to the data directory
  push:
    branches: [ main ]
    paths:
      - 'data/*'

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Pip install requirements.txt
      - uses: py-actions/py-dependency-install@v2

      # Runs a set of commands using the runners shell

      - name: Generate reports with Gitleaves
        run: |
          echo Add other actions to build, test, and deploy your project.
          gitleaves genreports

      - name: Figure out if anythings changed since the last run, this step helps with the cron job.
        id: changes
        run: echo ::set-output name=has_stuff_changed::$(git status --porcelain)

      - name: Commit if there are changes, otherwise this step is skipped.
        if: ${{ steps.changes.outputs.has_stuff_changed != '' }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add reports
          git commit -m "Leave report published to wiki." && git push
